apiVersion: v1
kind: ConfigMap
metadata:
  name: dashboard-config
  namespace: pxmx-dashboard
  labels:
    app.kubernetes.io/name: pxmx-dashboard
data:
  GITHUB_REPO: "shanmugara/pxmx-clusters"   # <-- replace with your owner/repo
  GITHUB_REF:  "main"
  PORT:        "5001"
  LOG_LEVEL:   "info"
  GUNICORN_WORKERS: "1"
  GUNICORN_THREADS: "4"
